### ISSUE TITLE
Assistance Needed

### ISSUE THREAD

**Issue by gchao101** [KaihuaQin/defi-mooc-lab2#5]
Hello!

I am in need of guidance for Lab 2.  I am a finance professional, not a programmer (though I have been learning to code in Solidity).  Could you please assist?

Many thanks!

Grace

**Comment by KaihuaQin** [comment]
Could you elaborate on the specific problems that you have? Thank you.

**Comment by gchao101** [comment]
To start with, I am not sure how to set up the nodeJS environment or install a docker…

**Comment by KaihuaQin** [comment]
Completely understand that setting up nodejs might be annoying for non-engineers. I would recommend checking out https://docs.docker.com/get-docker/ and installing docker.

**Comment by gchao101** [comment]
Thanks - I installed docker, but can't get the Docker Engine to start.  Do you have any suggestions for how to get it to work?

**Comment by KaihuaQin** [comment]
What's your OS, version, and what have you tried so far?

**Comment by gchao101** [comment]
I have Windows 10 pro, and I have tried turning on Hyper-V and purging some things.  Honestly, I really have no idea what to do on the set up front.  I think there are others in the same boat, based on discussions on Discord.   Would you be able to hold a virtual office hour for non-engineers to help us get set up for the assignment?

**Comment by hacklschorsch** [comment]
As per https://defi-learning.org/ you can also become a _Ninja_ by writing a blog post:

> 8 points for writing an article about relevant topic covered in this course [...]

HTH!

**Comment by gchao101** [comment]
Hi Florian,

Did you email me by accident?  I believe I have already wanted an NFT, as I’ve completed all the quizzes and labs. 

Thanks,

Grace

**Comment by hacklschorsch** [comment]
No, not by accident - you have an open issue ticket at https://github.com/KaihuaQin/defi-mooc-lab2/issues/5 . Please close the issue if it's not relevant anymore.

**Comment by gchao101** [comment]
Ah, ok.  Yes, I will close the issue.  One question: when will we receive our final grades and NFTs?

**Comment by hacklschorsch** [comment]
I can't say, I am just another student.

**Comment by gchao101** [comment]
Ok, no worries.  Have a great day!
